name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Job for GitHub
  release-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # Install Node.js
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Excecute semantic-release
      - name: Semantic Release for GitHub Code
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Job para versionar la imagen Docker
  release-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Authenticate with Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Run the script
      - name: Run Docker build script
        run: |
          chmod +x ./docker-versions.sh
          ./docker-versions.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}