name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Job for GitHub
  release-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # Install Node.js
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Execute semantic-release
      - name: Semantic Release for GitHub Code
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Notify Slack
      - name: Notify Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "Job release-code completed with status: ${{ job.status }} on branch: ${{ github.ref }}"
            }' \
            ${{ secrets.SLACK_WEBHOOK }}

  # Job para versionar la imagen Docker
  release-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download and install docker-credential-secretservice
      - name: Download docker-credential-secretservice
        run: |
          curl -fsSL https://github.com/docker/docker-credential-helpers/releases/latest/download/docker-credential-secretservice_linux_amd64 \
            -o /usr/local/bin/docker-credential-secretservice
          chmod +x /usr/local/bin/docker-credential-secretservice

      # Step 3: Configure Docker credential helper
      - name: Configure Docker credential helper
        run: |
          mkdir -p ~/.docker
          echo '{
            "credsStore": "secretservice"
          }' > ~/.docker/config.json

      # Step 4: Authenticate with Docker Hub
      - name: Authenticate with Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 5: Run the script
      - name: Run Docker build script
        run: |
          chmod +x ./docker-versions.sh
          ./docker-versions.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Notify Slack
      - name: Notify Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "Job release-docker completed with status: ${{ job.status }} on branch: ${{ github.ref }}"
            }' \
            ${{ secrets.SLACK_WEBHOOK }}